username: mobile-app-CI-CD
icon_url: https://avatars.githubusercontent.com/u/102382658?s=400&u=62e73f4cb845c48a07a19e03c6f84b721e40c0a6&v=4

pretext: "{{env.SLACK_MESSAGE_TITLE}}"
title: Mobile App CI/CD
title_link: https://github.com/ice-blockchain/mobile-app/actions

text: |
  {{#if description}}<{{diffUrl}}|`{{diffRef}}`> - {{description}}{{/if}}

fallback: |-
  [GitHub] {{workflow}} #{{runNumber}} {{jobName}} is {{jobStatus}}

fields:
  - title: Event
    value: "`{{eventName}}`"
    short: true
  - title: Status
    value: "{{jobStatus}}"
    short: true
  - title: Actor
    value: "<https://github.com/{{actor}}|{{actor}}>"
    short: true
  - title: Git Ref
    value: "<{{refUrl}}|`{{ref}}`> ({{refType}})"
    short: true
  - title: Environment
    value: "`{{env.APP_ENV}}`"
    short: true
  - title: Deployment
    value: "`{{env.DEPLOY_TARGET }}`"
    short: true
  - title: Workflow
    value: "<{{workflowUrl}}|{{workflow}}>"
    short: true
  - title: Job
    value: "<{{workflowRunUrl}}|{{jobName}}>"
    short: true
  - title: Run Number
    value: "{{runNumber}}"
    short: true
  - title: Run ID
    value: |-
      <{{workflowRunUrl}}|{{runId}}>
    short: true
  - title: Commits
    value: "{{#if payload.commits}}{{#each payload.commits}}<{{this.url}}|`{{truncate this.id 8}}`>{{/each}}{{/if}}"
    short: false

footer: >-
  <{{repositoryUrl}}|{{repositoryName}}> {{workflow}} #{{runNumber}}

colors:
  success: 'good'
  failure: 'danger'
  cancelled: 'warning'
  default: 'warning'

icons:
  success: ':white_check_mark:'
  failure: ':x:'
  cancelled: ':no_entry_sign:'
  skipped: ':heavy_minus_sign:'
  default: ':interrobang:'
