include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - lib/**.g.dart
    - lib/*.freezed.dart
    - build/**
    - lib/generated/**

  errors:
    invalid_annotation_target: ignore

linter:

  rules:

    # Conflicts with the convention used by flutter, which puts `Key key`
    # and `@required Widget child` last.
    always_put_required_named_parameters_first: false

    # No docs
    type_annotate_public_apis: false

    # Allow utility classes
    avoid_classes_with_only_static_members: false

    # Group dependencies
    sort_pub_dependencies: false

    # Let only setters exist
    avoid_setters_without_getters: false

    # Use bools in positional args
    avoid_positional_boolean_parameters: false

    ############################################################

    # Make constructors the first thing in every class
    sort_constructors_first: true

    # Fast literals
    prefer_single_quotes: true

    # Follow the Flutter code style, which prefers types everywhere
    always_specify_types: true