include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint

  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart
    - build/**
    - scripts/**
    - lib/generated/**

  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    public_member_api_docs: false
    flutter_style_todos: false
    comment_references: false
    avoid_setters_without_getters: false
    lines_longer_than_80_chars: false
    one_member_abstracts: false
