targets:
  $default:
    sources:
      exclude:
        - lib/**/**.g.dart

    builders:

      freezed:
        options:
          explicit_to_json: true
          copy_with: false
          equal: false
