targets:
  $default:
    auto_apply_builders: false
    builders:         
      freezed:freezed:
        generate_for:
          include:
            - lib/**.c.dart
      json_serializable:json_serializable:
        generate_for:
          include:
            - lib/**.c.dart
      riverpod_generator:riverpod_generator:
        generate_for:
          include:
            - lib/**.c.dart
      go_router_builder:go_router_builder:
        generate_for:
          include:
            - lib/app/router/**.c.dart
      flutter_gen_runner:
        enabled: true
      drift_dev:
        generate_for:
          include:
            - lib/**/database/**.c.dart
        options:
          use_sql_column_name_as_json_key : true
          databases:
            chat_database: lib/app/features/chat/model/database/chat_database.c.dart
            notifications_database: lib/app/features/feed/notifications/data/database/notifications_database.c.dart
            wallets_database: lib/app/features/wallets/data/database/wallets_database.c.dart
