targets:
  $default:
    builders:
      freezed:freezed:
        generate_for:
          include:
            - lib/**.c.dart
          exclude:
            - lib/generated/**
            - lib/widgetbook/**
            - lib/l10n/**
            - lib/main.dart
      json_serializable:json_serializable:
        generate_for:
          include:
            - lib/**.c.dart
          exclude:
            - lib/generated/**
            - lib/widgetbook/**
            - lib/l10n/**
            - lib/main.dart
      riverpod_generator:riverpod_generator:
        generate_for:
          include:
            - lib/**.c.dart
          exclude:
            - lib/generated/**
            - lib/widgetbook/**
            - lib/l10n/**
            - lib/main.dart
      go_router_builder:go_router_builder:
        generate_for:
          include:
            - lib/**.c.dart
          exclude:
            - lib/generated/**
            - lib/widgetbook/**
            - lib/l10n/**
            - lib/main.dart
