targets:
  $default:
    auto_apply_builders: false
    builders:
      freezed:freezed:
        generate_for:
          include:
            - lib/**.f.dart
            - lib/**.m.dart
      json_serializable:json_serializable:
        generate_for:
          include:
            - lib/**.f.dart
            - lib/**.m.dart
      riverpod_generator:riverpod_generator:
        generate_for:
          include:
            - lib/**.r.dart
            - lib/**.m.dart
      go_router_builder:go_router_builder:
        generate_for:
          include:
            - lib/app/router/**.gr.dart
      flutter_gen_runner:
        enabled: true
      drift_dev:
        generate_for:
          include:
            - lib/**/database/**.d.dart
            - lib/**.m.dart
        options:
          use_sql_column_name_as_json_key: true
          databases:
            chat_database: lib/app/features/chat/model/database/chat_database.d.dart
            notifications_database: lib/app/features/feed/notifications/data/database/notifications_database.d.dart
            wallets_database: lib/app/features/wallets/data/database/wallets_database.d.dart
            event_messages_database: lib/app/features/ion_connect/database/event_messages_database.d.dart
            following_feed_database: lib/app/features/feed/data/database/following_feed_database/following_feed_database.d.dart
