targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/src/**/dtos/*.dart
            - lib/src/**/models/*.dart
            - lib/src/**/types/*.dart

            - lib/src/**/services/**/models/*.dart
          exclude:
            - "**.g.dart"
            - "**.freezed.dart"
            - lib/src/**/*.g.dart
            - lib/src/**/*.freezed.dart

      json_serializable:
        generate_for:
          include:
            - lib/src/**/dtos/*.dart
            - lib/src/**/models/*.dart
            - lib/src/**/types/*.dart
            - lib/src/**/services/**/models/*.dart
          exclude:
            - "**.freezed.dart"
            - "**.g.dart"
            - lib/src/**/*.g.dart
            - lib/src/**/*.freezed.dart
            - "**/service.dart"
            - "**/service_locator.dart"
            - "**/data_source.dart"
        options:
          create_to_json: true
          explicit_to_json: true
