targets:
  $default:
    builders:
      freezed:freezed:
        generate_for:
          include:
            - lib/**.f.dart
            - lib/**.m.dart
      json_serializable:json_serializable:
        generate_for:
          include:
            - lib/**.f.dart
            - lib/**.j.dart  
            - lib/**.m.dart
        options:
          create_to_json: true
          explicit_to_json: true
