# pubspec.yaml
name: ion_lint_rules
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  # we will use analyzer for inspecting Dart files
  analyzer: any
  analyzer_plugin: any
  # custom_lint_builder will give us tools for writing lints
  custom_lint_builder: ^0.6.10
  flutter_test:
    sdk: flutter