// SPDX-License-Identifier: ice License 1.0

import 'package:ice/app/features/user/model/user_data.dart';

const Map<String, UserData> mockedUserData = {
  '001': UserData(
    id: '001',
    name: 'johndoe',
    about: 'A tech enthusiast and developer based in San Francisco.',
    picture: 'https://i.pravatar.cc/150?u=john_doe',
    displayName: 'John D',
    website: 'https://johndoe.dev',
    banner: 'https://i.pravatar.cc/750?u=john_banner',
    verified: true,
  ),
  '002': UserData(
    id: '002',
    name: 'janesmith',
    about: 'Designer and UX expert with a passion for creating user-friendly apps.',
    picture: 'https://i.pravatar.cc/150?u=jane_smith',
    displayName: 'Jane UX',
    website: 'https://janesmith.com',
    nft: true,
  ),
  '003': UserData(
    id: '003',
    name: 'tombrown',
    about: 'Freelance photographer capturing moments around the world.',
    picture: 'https://i.pravatar.cc/150?u=tom_brown',
    displayName: 'Tom Brown',
    banner: 'https://i.pravatar.cc/750?u=tom_banner',
    verified: true,
  ),
  '004': UserData(
    id: '004',
    name: 'emilyjohnson',
    about: 'Coffee lover, blogger, and content creator.',
    picture: 'https://i.pravatar.cc/150?u=emily_johnson',
  ),
  '005': UserData(
    id: '005',
    name: 'michaellee',
    about: 'Data scientist exploring the world of machine learning and AI.',
    picture: 'https://i.pravatar.cc/150?u=michael_lee_11',
    displayName: 'ML Michael',
    website: 'https://michaellee.ai',
    verified: true,
    nft: true,
  ),
  '006': UserData(
    id: '006',
    name: 'alicegreen',
    about: 'Yoga instructor and wellness advocate.',
    picture: 'https://i.pravatar.cc/150?u=alice_green',
  ),
  '007': UserData(
    id: '007',
    name: 'robertwhite',
    about: 'Professional gamer and eSports coach.',
    picture: 'https://i.pravatar.cc/150?u=robert_white',
    displayName: 'R White Gamer',
    website: 'https://rwhitegaming.com',
  ),
  '008': UserData(
    id: '008',
    name: 'sophieblack',
    about: 'Fashion blogger sharing the latest trends and style tips.',
    picture: 'https://i.pravatar.cc/150?u=sophie_black',
    displayName: 'Soph Style',
    banner: 'https://i.pravatar.cc/750?u=sophie_banner',
    nft: true,
  ),
  '009': UserData(
    id: '009',
    name: 'danielharris',
    about: 'Full-stack developer working on cutting-edge web technologies.',
    picture: 'https://i.pravatar.cc/150?u=daniel_harris',
  ),
  '010': UserData(
    id: '010',
    name: 'jessicadavis',
    about: 'Food critic and recipe developer.',
    picture: 'https://i.pravatar.cc/150?u=jessica_davis',
    displayName: 'Jessie Eats',
    website: 'https://jessicadavisfood.com',
    verified: true,
    nft: true,
  ),
  '011': UserData(
    id: '011',
    name: 'oliverwilson',
    about: 'Travel blogger exploring hidden gems around the globe.',
    picture: 'https://i.pravatar.cc/150?u=oliver_wilson',
  ),
  '012': UserData(
    id: '012',
    name: 'liammartin',
    about: 'Marketing expert with a focus on digital strategy.',
    picture: 'https://i.pravatar.cc/150?u=liam_martin',
    displayName: 'Liam Digital',
    website: 'https://liammarketing.com',
  ),
  '013': UserData(
    id: '013',
    name: 'sophiawalker',
    about: 'Tech journalist covering the latest in startups and innovation.',
    picture: 'https://i.pravatar.cc/150?u=sophia_walker',
  ),
  '014': UserData(
    id: '014',
    name: 'elijahthompson',
    about: 'Musician and composer creating original soundtracks.',
    picture: 'https://i.pravatar.cc/150?u=elijah_thompson',
    displayName: 'Eli Composer',
    banner: 'https://i.pravatar.cc/750?u=elijah_banner',
  ),
  '015': UserData(
    id: '015',
    name: 'miaclark',
    about: 'Startup founder building the next big thing in fintech.',
    picture: 'https://i.pravatar.cc/150?u=mia_clark',
  ),
  '016': UserData(
    id: '016',
    name: 'lucasadams',
    about: 'Fitness coach helping people achieve their health goals.',
    picture: 'https://i.pravatar.cc/150?u=lucas_adams',
  ),
  '017': UserData(
    id: '017',
    name: 'isabellahall',
    about: 'Artist and illustrator bringing stories to life through art.',
    picture: 'https://i.pravatar.cc/150?u=isabella_hall',
    displayName: 'Bella Art',
    banner: 'https://i.pravatar.cc/750?u=isabella_banner',
  ),
  '018': UserData(
    id: '018',
    name: 'henryscott',
    about: 'Entrepreneur and investor passionate about tech startups.',
    picture: 'https://i.pravatar.cc/150?u=henry_scott',
    website: 'https://henryscottventures.com',
  ),
  '019': UserData(
    id: '019',
    name: 'graceyoung',
    about: 'Environmentalist working towards a sustainable future.',
    picture: 'https://i.pravatar.cc/150?u=grace_young',
    nft: true,
  ),
  '020': UserData(
    id: '020',
    name: 'ethanmiller',
    about: 'Podcaster discussing the intersection of culture and technology.',
    picture: 'https://i.pravatar.cc/150?u=ethan_miller',
    displayName: 'Tech Talk Ethan',
    website: 'https://techtalkpod.com',
  ),
};
