// SPDX-License-Identifier: ice License 1.0

import 'package:freezed_annotation/freezed_annotation.dart';

part 'countries.f.freezed.dart';

@freezed
class Country with _$Country {
  const factory Country({
    required String name,
    required String flag,
    required String isoCode,
    required String iddCode,
  }) = _Country;
}

const List<Country> countriesData = [
  Country(name: 'Andorra', flag: '🇦🇩', isoCode: 'AD', iddCode: '+376'),
  Country(
    name: 'United Arab Emirates',
    flag: '🇦🇪',
    isoCode: 'AE',
    iddCode: '+971',
  ),
  Country(name: 'Afghanistan', flag: '🇦🇫', isoCode: 'AF', iddCode: '+93'),
  Country(
    name: 'Antigua and Barbuda',
    flag: '🇦🇬',
    isoCode: 'AG',
    iddCode: '+1',
  ),
  Country(name: 'Anguilla', flag: '🇦🇮', isoCode: 'AI', iddCode: '+1'),
  Country(name: 'Albania', flag: '🇦🇱', isoCode: 'AL', iddCode: '+355'),
  Country(name: 'Armenia', flag: '🇦🇲', isoCode: 'AM', iddCode: '+374'),
  Country(name: 'Angola', flag: '🇦🇴', isoCode: 'AO', iddCode: '+244'),
  Country(name: 'Antarctica', flag: '🇦🇶', isoCode: 'AQ', iddCode: '+672'),
  Country(name: 'Argentina', flag: '🇦🇷', isoCode: 'AR', iddCode: '+54'),
  Country(name: 'American Samoa', flag: '🇦🇸', isoCode: 'AS', iddCode: '+1'),
  Country(name: 'Austria', flag: '🇦🇹', isoCode: 'AT', iddCode: '+43'),
  Country(name: 'Australia', flag: '🇦🇺', isoCode: 'AU', iddCode: '+61'),
  Country(name: 'Aruba', flag: '🇦🇼', isoCode: 'AW', iddCode: '+297'),
  Country(name: 'Aland Islands', flag: '🇦🇽', isoCode: 'AX', iddCode: '+358'),
  Country(name: 'Azerbaijan', flag: '🇦🇿', isoCode: 'AZ', iddCode: '+994'),
  Country(
    name: 'Bosnia and Herzegovina',
    flag: '🇧🇦',
    isoCode: 'BA',
    iddCode: '+387',
  ),
  Country(name: 'Barbados', flag: '🇧🇧', isoCode: 'BB', iddCode: '+1'),
  Country(name: 'Bangladesh', flag: '🇧🇩', isoCode: 'BD', iddCode: '+880'),
  Country(name: 'Belgium', flag: '🇧🇪', isoCode: 'BE', iddCode: '+32'),
  Country(name: 'Burkina Faso', flag: '🇧🇫', isoCode: 'BF', iddCode: '+226'),
  Country(name: 'Bulgaria', flag: '🇧🇬', isoCode: 'BG', iddCode: '+359'),
  Country(name: 'Bahrain', flag: '🇧🇭', isoCode: 'BH', iddCode: '+973'),
  Country(name: 'Burundi', flag: '🇧🇮', isoCode: 'BI', iddCode: '+257'),
  Country(name: 'Benin', flag: '🇧🇯', isoCode: 'BJ', iddCode: '+229'),
  Country(
    name: 'Saint Barthelemy',
    flag: '🇧🇱',
    isoCode: 'BL',
    iddCode: '+590',
  ),
  Country(name: 'Bermuda', flag: '🇧🇲', isoCode: 'BM', iddCode: '+1'),
  Country(
    name: 'Brunei Darussalam',
    flag: '🇧🇳',
    isoCode: 'BN',
    iddCode: '+673',
  ),
  Country(name: 'Bolivia', flag: '🇧🇴', isoCode: 'BO', iddCode: '+591'),
  Country(
    name: 'Bonaire, Sint Eustatius and Saba',
    flag: '🇧🇶',
    isoCode: 'BQ',
    iddCode: '+599',
  ),
  Country(name: 'Brazil', flag: '🇧🇷', isoCode: 'BR', iddCode: '+55'),
  Country(name: 'Bahamas', flag: '🇧🇸', isoCode: 'BS', iddCode: '+1'),
  Country(name: 'Bhutan', flag: '🇧🇹', isoCode: 'BT', iddCode: '+975'),
  Country(name: 'Bouvet Island', flag: '🇧🇻', isoCode: 'BV', iddCode: '+55'),
  Country(name: 'Botswana', flag: '🇧🇼', isoCode: 'BW', iddCode: '+267'),
  Country(name: 'Belarus', flag: '🇧🇾', isoCode: 'BY', iddCode: '+375'),
  Country(name: 'Belize', flag: '🇧🇿', isoCode: 'BZ', iddCode: '+501'),
  Country(name: 'Canada', flag: '🇨🇦', isoCode: 'CA', iddCode: '+1'),
  Country(
    name: 'Cocos (Keeling) Islands',
    flag: '🇨🇨',
    isoCode: 'CC',
    iddCode: '+61',
  ),
  Country(
    name: 'Democratic Republic of the Congo',
    flag: '🇨🇩',
    isoCode: 'CD',
    iddCode: '+243',
  ),
  Country(
    name: 'Central African Republic',
    flag: '🇨🇫',
    isoCode: 'CF',
    iddCode: '+236',
  ),
  Country(name: 'Congo', flag: '🇨🇬', isoCode: 'CG', iddCode: '+242'),
  Country(name: 'Switzerland', flag: '🇨🇭', isoCode: 'CH', iddCode: '+41'),
  Country(name: "Cote D'ivoire", flag: '🇨🇮', isoCode: 'CI', iddCode: '+225'),
  Country(name: 'Cook Islands', flag: '🇨🇰', isoCode: 'CK', iddCode: '+682'),
  Country(name: 'Chile', flag: '🇨🇱', isoCode: 'CL', iddCode: '+56'),
  Country(name: 'Cameroon', flag: '🇨🇲', isoCode: 'CM', iddCode: '+237'),
  Country(name: 'China', flag: '🇨🇳', isoCode: 'CN', iddCode: '+86'),
  Country(name: 'Colombia', flag: '🇨🇴', isoCode: 'CO', iddCode: '+57'),
  Country(name: 'Costa Rica', flag: '🇨🇷', isoCode: 'CR', iddCode: '+506'),
  Country(name: 'Cuba', flag: '🇨🇺', isoCode: 'CU', iddCode: '+53'),
  Country(name: 'Cabo Verde', flag: '🇨🇻', isoCode: 'CV', iddCode: '+238'),
  Country(name: 'Curacao', flag: '🇨🇼', isoCode: 'CW', iddCode: '+599'),
  Country(
    name: 'Christmas Island',
    flag: '🇨🇽',
    isoCode: 'CX',
    iddCode: '+61',
  ),
  Country(name: 'Cyprus', flag: '🇨🇾', isoCode: 'CY', iddCode: '+357'),
  Country(name: 'Czechia', flag: '🇨🇿', isoCode: 'CZ', iddCode: '+420'),
  Country(name: 'Germany', flag: '🇩🇪', isoCode: 'DE', iddCode: '+49'),
  Country(name: 'Djibouti', flag: '🇩🇯', isoCode: 'DJ', iddCode: '+253'),
  Country(name: 'Denmark', flag: '🇩🇰', isoCode: 'DK', iddCode: '+45'),
  Country(name: 'Dominica', flag: '🇩🇲', isoCode: 'DM', iddCode: '+1'),
  Country(
    name: 'Dominican Republic',
    flag: '🇩🇴',
    isoCode: 'DO',
    iddCode: '+1',
  ),
  Country(name: 'Algeria', flag: '🇩🇿', isoCode: 'DZ', iddCode: '+213'),
  Country(name: 'Ecuador', flag: '🇪🇨', isoCode: 'EC', iddCode: '+593'),
  Country(name: 'Estonia', flag: '🇪🇪', isoCode: 'EE', iddCode: '+372'),
  Country(name: 'Egypt', flag: '🇪🇬', isoCode: 'EG', iddCode: '+20'),
  Country(name: 'Western Sahara', flag: '🇪🇭', isoCode: 'EH', iddCode: '+212'),
  Country(name: 'Eritrea', flag: '🇪🇷', isoCode: 'ER', iddCode: '+291'),
  Country(name: 'Spain', flag: '🇪🇸', isoCode: 'ES', iddCode: '+34'),
  Country(name: 'Ethiopia', flag: '🇪🇹', isoCode: 'ET', iddCode: '+251'),
  Country(name: 'Finland', flag: '🇫🇮', isoCode: 'FI', iddCode: '+358'),
  Country(name: 'Fiji', flag: '🇫🇯', isoCode: 'FJ', iddCode: '+679'),
  Country(
    name: 'Falkland Islands (Malvinas)',
    flag: '🇫🇰',
    isoCode: 'FK',
    iddCode: '+500',
  ),
  Country(
    name: 'Federated States of Micronesia',
    flag: '🇫🇲',
    isoCode: 'FM',
    iddCode: '+691',
  ),
  Country(name: 'Faroe Islands', flag: '🇫🇴', isoCode: 'FO', iddCode: '+298'),
  Country(name: 'France', flag: '🇫🇷', isoCode: 'FR', iddCode: '+33'),
  Country(name: 'Gabon', flag: '🇬🇦', isoCode: 'GA', iddCode: '+241'),
  Country(name: 'United Kingdom', flag: '🇬🇧', isoCode: 'GB', iddCode: '+44'),
  Country(name: 'Grenada', flag: '🇬🇩', isoCode: 'GD', iddCode: '+1'),
  Country(name: 'Georgia', flag: '🇬🇪', isoCode: 'GE', iddCode: '+995'),
  Country(name: 'French Guiana', flag: '🇬🇫', isoCode: 'GF', iddCode: '+594'),
  Country(name: 'Guernsey', flag: '🇬🇬', isoCode: 'GG', iddCode: '+44'),
  Country(name: 'Ghana', flag: '🇬🇭', isoCode: 'GH', iddCode: '+233'),
  Country(name: 'Gibraltar', flag: '🇬🇮', isoCode: 'GI', iddCode: '+350'),
  Country(name: 'Greenland', flag: '🇬🇱', isoCode: 'GL', iddCode: '+299'),
  Country(name: 'Gambia', flag: '🇬🇲', isoCode: 'GM', iddCode: '+220'),
  Country(name: 'Guinea', flag: '🇬🇳', isoCode: 'GN', iddCode: '+224'),
  Country(name: 'Guadeloupe', flag: '🇬🇵', isoCode: 'GP', iddCode: '+590'),
  Country(
    name: 'Equatorial Guinea',
    flag: '🇬🇶',
    isoCode: 'GQ',
    iddCode: '+240',
  ),
  Country(name: 'Greece', flag: '🇬🇷', isoCode: 'GR', iddCode: '+30'),
  Country(
    name: 'South Georgia and The South Sandwich Islands',
    flag: '🇬🇸',
    isoCode: 'GS',
    iddCode: '+500',
  ),
  Country(name: 'Guatemala', flag: '🇬🇹', isoCode: 'GT', iddCode: '+502'),
  Country(name: 'Guam', flag: '🇬🇺', isoCode: 'GU', iddCode: '+1'),
  Country(name: 'Guinea-Bissau', flag: '🇬🇼', isoCode: 'GW', iddCode: '+245'),
  Country(name: 'Guyana', flag: '🇬🇾', isoCode: 'GY', iddCode: '+592'),
  Country(name: 'Hong Kong', flag: '🇭🇰', isoCode: 'HK', iddCode: '+852'),
  Country(
    name: 'Heard Island and Mcdonald Islands',
    flag: '🇭🇲',
    isoCode: 'HM',
    iddCode: '+672',
  ),
  Country(name: 'Honduras', flag: '🇭🇳', isoCode: 'HN', iddCode: '+504'),
  Country(name: 'Croatia', flag: '🇭🇷', isoCode: 'HR', iddCode: '+385'),
  Country(name: 'Haiti', flag: '🇭🇹', isoCode: 'HT', iddCode: '+509'),
  Country(name: 'Hungary', flag: '🇭🇺', isoCode: 'HU', iddCode: '+36'),
  Country(name: 'Indonesia', flag: '🇮🇩', isoCode: 'ID', iddCode: '+62'),
  Country(name: 'Ireland', flag: '🇮🇪', isoCode: 'IE', iddCode: '+353'),
  Country(name: 'Israel', flag: '🇮🇱', isoCode: 'IL', iddCode: '+972'),
  Country(name: 'Isle of Man', flag: '🇮🇲', isoCode: 'IM', iddCode: '+44'),
  Country(name: 'India', flag: '🇮🇳', isoCode: 'IN', iddCode: '+91'),
  Country(
    name: 'British Indian Ocean Territory',
    flag: '🇮🇴',
    isoCode: 'IO',
    iddCode: '+246',
  ),
  Country(name: 'Iraq', flag: '🇮🇶', isoCode: 'IQ', iddCode: '+964'),
  Country(
    name: 'Islamic Republic of Iran',
    flag: '🇮🇷',
    isoCode: 'IR',
    iddCode: '+98',
  ),
  Country(name: 'Iceland', flag: '🇮🇸', isoCode: 'IS', iddCode: '+354'),
  Country(name: 'Italy', flag: '🇮🇹', isoCode: 'IT', iddCode: '+39'),
  Country(name: 'Jersey', flag: '🇯🇪', isoCode: 'JE', iddCode: '+44'),
  Country(name: 'Jamaica', flag: '🇯🇲', isoCode: 'JM', iddCode: '+1'),
  Country(name: 'Jordan', flag: '🇯🇴', isoCode: 'JO', iddCode: '+962'),
  Country(name: 'Japan', flag: '🇯🇵', isoCode: 'JP', iddCode: '+81'),
  Country(name: 'Kenya', flag: '🇰🇪', isoCode: 'KE', iddCode: '+254'),
  Country(name: 'Kyrgyzstan', flag: '🇰🇬', isoCode: 'KG', iddCode: '+996'),
  Country(name: 'Cambodia', flag: '🇰🇭', isoCode: 'KH', iddCode: '+855'),
  Country(name: 'Kiribati', flag: '🇰🇮', isoCode: 'KI', iddCode: '+686'),
  Country(name: 'Comoros', flag: '🇰🇲', isoCode: 'KM', iddCode: '+269'),
  Country(
    name: 'Saint Kitts and Nevis',
    flag: '🇰🇳',
    isoCode: 'KN',
    iddCode: '+1',
  ),
  Country(
    name: "Democratic People's Republic of Korea",
    flag: '🇰🇵',
    isoCode: 'KP',
    iddCode: '+850',
  ),
  Country(
    name: 'Republic of Korea',
    flag: '🇰🇷',
    isoCode: 'KR',
    iddCode: '+82',
  ),
  Country(
    name: 'Republic of Kosovo',
    flag: '🇽🇰',
    isoCode: 'XK',
    iddCode: '+383',
  ),
  Country(name: 'Kuwait', flag: '🇰🇼', isoCode: 'KW', iddCode: '+965'),
  Country(name: 'Cayman Islands', flag: '🇰🇾', isoCode: 'KY', iddCode: '+1'),
  Country(name: 'Kazakhstan', flag: '🇰🇿', isoCode: 'KZ', iddCode: '+7'),
  Country(
    name: "Lao People's Democratic Republic",
    flag: '🇱🇦',
    isoCode: 'LA',
    iddCode: '+856',
  ),
  Country(name: 'Lebanon', flag: '🇱🇧', isoCode: 'LB', iddCode: '+961'),
  Country(name: 'Saint Lucia', flag: '🇱🇨', isoCode: 'LC', iddCode: '+1'),
  Country(name: 'Liechtenstein', flag: '🇱🇮', isoCode: 'LI', iddCode: '+423'),
  Country(name: 'Sri Lanka', flag: '🇱🇰', isoCode: 'LK', iddCode: '+94'),
  Country(name: 'Liberia', flag: '🇱🇷', isoCode: 'LR', iddCode: '+231'),
  Country(name: 'Lesotho', flag: '🇱🇸', isoCode: 'LS', iddCode: '+266'),
  Country(name: 'Lithuania', flag: '🇱🇹', isoCode: 'LT', iddCode: '+370'),
  Country(name: 'Luxembourg', flag: '🇱🇺', isoCode: 'LU', iddCode: '+352'),
  Country(name: 'Latvia', flag: '🇱🇻', isoCode: 'LV', iddCode: '+371'),
  Country(name: 'Libya', flag: '🇱🇾', isoCode: 'LY', iddCode: '+218'),
  Country(name: 'Morocco', flag: '🇲🇦', isoCode: 'MA', iddCode: '+212'),
  Country(name: 'Monaco', flag: '🇲🇨', isoCode: 'MC', iddCode: '+377'),
  Country(
    name: 'Republic of Moldova',
    flag: '🇲🇩',
    isoCode: 'MD',
    iddCode: '+373',
  ),
  Country(name: 'Montenegro', flag: '🇲🇪', isoCode: 'ME', iddCode: '+382'),
  Country(
    name: 'Saint Martin (French Part)',
    flag: '🇲🇫',
    isoCode: 'MF',
    iddCode: '+590',
  ),
  Country(name: 'Madagascar', flag: '🇲🇬', isoCode: 'MG', iddCode: '+261'),
  Country(
    name: 'Marshall Islands',
    flag: '🇲🇭',
    isoCode: 'MH',
    iddCode: '+692',
  ),
  Country(
    name: 'North Macedonia',
    flag: '🇲🇰',
    isoCode: 'MK',
    iddCode: '+389',
  ),
  Country(name: 'Mali', flag: '🇲🇱', isoCode: 'ML', iddCode: '+223'),
  Country(name: 'Myanmar', flag: '🇲🇲', isoCode: 'MM', iddCode: '+95'),
  Country(name: 'Mongolia', flag: '🇲🇳', isoCode: 'MN', iddCode: '+976'),
  Country(name: 'Macao', flag: '🇲🇴', isoCode: 'MO', iddCode: '+853'),
  Country(
    name: 'Northern Mariana Islands',
    flag: '🇲🇵',
    isoCode: 'MP',
    iddCode: '+1',
  ),
  Country(name: 'Martinique', flag: '🇲🇶', isoCode: 'MQ', iddCode: '+596'),
  Country(name: 'Mauritania', flag: '🇲🇷', isoCode: 'MR', iddCode: '+222'),
  Country(name: 'Montserrat', flag: '🇲🇸', isoCode: 'MS', iddCode: '+1'),
  Country(name: 'Malta', flag: '🇲🇹', isoCode: 'MT', iddCode: '+356'),
  Country(name: 'Mauritius', flag: '🇲🇺', isoCode: 'MU', iddCode: '+230'),
  Country(name: 'Maldives', flag: '🇲🇻', isoCode: 'MV', iddCode: '+960'),
  Country(name: 'Malawi', flag: '🇲🇼', isoCode: 'MW', iddCode: '+265'),
  Country(name: 'Mexico', flag: '🇲🇽', isoCode: 'MX', iddCode: '+52'),
  Country(name: 'Malaysia', flag: '🇲🇾', isoCode: 'MY', iddCode: '+60'),
  Country(name: 'Mozambique', flag: '🇲🇿', isoCode: 'MZ', iddCode: '+258'),
  Country(name: 'Namibia', flag: '🇳🇦', isoCode: 'NA', iddCode: '+264'),
  Country(name: 'New Caledonia', flag: '🇳🇨', isoCode: 'NC', iddCode: '+687'),
  Country(name: 'Niger', flag: '🇳🇪', isoCode: 'NE', iddCode: '+227'),
  Country(name: 'Norfolk Island', flag: '🇳🇫', isoCode: 'NF', iddCode: '+672'),
  Country(name: 'Nigeria', flag: '🇳🇬', isoCode: 'NG', iddCode: '+234'),
  Country(name: 'Nicaragua', flag: '🇳🇮', isoCode: 'NI', iddCode: '+505'),
  Country(name: 'Netherlands', flag: '🇳🇱', isoCode: 'NL', iddCode: '+31'),
  Country(name: 'Norway', flag: '🇳🇴', isoCode: 'NO', iddCode: '+47'),
  Country(name: 'Nepal', flag: '🇳🇵', isoCode: 'NP', iddCode: '+977'),
  Country(name: 'Nauru', flag: '🇳🇷', isoCode: 'NR', iddCode: '+674'),
  Country(name: 'Niue', flag: '🇳🇺', isoCode: 'NU', iddCode: '+683'),
  Country(name: 'New Zealand', flag: '🇳🇿', isoCode: 'NZ', iddCode: '+64'),
  Country(name: 'Oman', flag: '🇴🇲', isoCode: 'OM', iddCode: '+968'),
  Country(name: 'Panama', flag: '🇵🇦', isoCode: 'PA', iddCode: '+507'),
  Country(name: 'Peru', flag: '🇵🇪', isoCode: 'PE', iddCode: '+51'),
  Country(
    name: 'French Polynesia',
    flag: '🇵🇫',
    isoCode: 'PF',
    iddCode: '+689',
  ),
  Country(
    name: 'Papua New Guinea',
    flag: '🇵🇬',
    isoCode: 'PG',
    iddCode: '+675',
  ),
  Country(name: 'Philippines', flag: '🇵🇭', isoCode: 'PH', iddCode: '+63'),
  Country(name: 'Pakistan', flag: '🇵🇰', isoCode: 'PK', iddCode: '+92'),
  Country(name: 'Poland', flag: '🇵🇱', isoCode: 'PL', iddCode: '+48'),
  Country(
    name: 'Saint Pierre and Miquelon',
    flag: '🇵🇲',
    isoCode: 'PM',
    iddCode: '+508',
  ),
  Country(name: 'Pitcairn', flag: '🇵🇳', isoCode: 'PN', iddCode: '+64'),
  Country(name: 'Puerto Rico', flag: '🇵🇷', isoCode: 'PR', iddCode: '+1'),
  Country(
    name: 'State of Palestine',
    flag: '🇵🇸',
    isoCode: 'PS',
    iddCode: '+970',
  ),
  Country(name: 'Portugal', flag: '🇵🇹', isoCode: 'PT', iddCode: '+351'),
  Country(name: 'Palau', flag: '🇵🇼', isoCode: 'PW', iddCode: '+680'),
  Country(name: 'Paraguay', flag: '🇵🇾', isoCode: 'PY', iddCode: '+595'),
  Country(name: 'Qatar', flag: '🇶🇦', isoCode: 'QA', iddCode: '+974'),
  Country(name: 'Reunion', flag: '🇷🇪', isoCode: 'RE', iddCode: '+262'),
  Country(name: 'Romania', flag: '🇷🇴', isoCode: 'RO', iddCode: '+40'),
  Country(name: 'Serbia', flag: '🇷🇸', isoCode: 'RS', iddCode: '+381'),
  Country(
    name: 'Russian Federation',
    flag: '🇷🇺',
    isoCode: 'RU',
    iddCode: '+7',
  ),
  Country(name: 'Rwanda', flag: '🇷🇼', isoCode: 'RW', iddCode: '+250'),
  Country(name: 'Saudi Arabia', flag: '🇸🇦', isoCode: 'SA', iddCode: '+966'),
  Country(
    name: 'Solomon Islands',
    flag: '🇸🇧',
    isoCode: 'SB',
    iddCode: '+677',
  ),
  Country(name: 'Seychelles', flag: '🇸🇨', isoCode: 'SC', iddCode: '+248'),
  Country(name: 'Sudan', flag: '🇸🇩', isoCode: 'SD', iddCode: '+249'),
  Country(name: 'Sweden', flag: '🇸🇪', isoCode: 'SE', iddCode: '+46'),
  Country(name: 'Singapore', flag: '🇸🇬', isoCode: 'SG', iddCode: '+65'),
  Country(
    name: 'Saint Helena, Ascension and Tristan Da Cunha',
    flag: '🇸🇭',
    isoCode: 'SH',
    iddCode: '+290',
  ),
  Country(name: 'Slovenia', flag: '🇸🇮', isoCode: 'SI', iddCode: '+386'),
  Country(
    name: 'Svalbard and Jan Mayen',
    flag: '🇸🇯',
    isoCode: 'SJ',
    iddCode: '+47',
  ),
  Country(name: 'Slovakia', flag: '🇸🇰', isoCode: 'SK', iddCode: '+421'),
  Country(name: 'Sierra Leone', flag: '🇸🇱', isoCode: 'SL', iddCode: '+232'),
  Country(name: 'San Marino', flag: '🇸🇲', isoCode: 'SM', iddCode: '+378'),
  Country(name: 'Senegal', flag: '🇸🇳', isoCode: 'SN', iddCode: '+221'),
  Country(name: 'Somalia', flag: '🇸🇴', isoCode: 'SO', iddCode: '+252'),
  Country(name: 'Suriname', flag: '🇸🇷', isoCode: 'SR', iddCode: '+597'),
  Country(name: 'South Sudan', flag: '🇸🇸', isoCode: 'SS', iddCode: '+211'),
  Country(
    name: 'Sao Tome and Principe',
    flag: '🇸🇹',
    isoCode: 'ST',
    iddCode: '+239',
  ),
  Country(name: 'El Salvador', flag: '🇸🇻', isoCode: 'SV', iddCode: '+503'),
  Country(
    name: 'Sint Maarten (Dutch Part)',
    flag: '🇸🇽',
    isoCode: 'SX',
    iddCode: '+1',
  ),
  Country(
    name: 'Syrian Arab Republic',
    flag: '🇸🇾',
    isoCode: 'SY',
    iddCode: '+963',
  ),
  Country(name: 'Eswatini', flag: '🇸🇿', isoCode: 'SZ', iddCode: '+268'),
  Country(
    name: 'Turks and Caicos Islands',
    flag: '🇹🇨',
    isoCode: 'TC',
    iddCode: '+1',
  ),
  Country(name: 'Chad', flag: '🇹🇩', isoCode: 'TD', iddCode: '+235'),
  Country(
    name: 'French Southern Territories',
    flag: '🇹🇫',
    isoCode: 'TF',
    iddCode: '+672',
  ),
  Country(name: 'Togo', flag: '🇹🇬', isoCode: 'TG', iddCode: '+228'),
  Country(name: 'Thailand', flag: '🇹🇭', isoCode: 'TH', iddCode: '+66'),
  Country(name: 'Tajikistan', flag: '🇹🇯', isoCode: 'TJ', iddCode: '+992'),
  Country(name: 'Tokelau', flag: '🇹🇰', isoCode: 'TK', iddCode: '+690'),
  Country(name: 'Timor-Leste', flag: '🇹🇱', isoCode: 'TL', iddCode: '+670'),
  Country(name: 'Turkmenistan', flag: '🇹🇲', isoCode: 'TM', iddCode: '+993'),
  Country(name: 'Tunisia', flag: '🇹🇳', isoCode: 'TN', iddCode: '+216'),
  Country(name: 'Tonga', flag: '🇹🇴', isoCode: 'TO', iddCode: '+676'),
  Country(name: 'Turkey', flag: '🇹🇷', isoCode: 'TR', iddCode: '+90'),
  Country(
    name: 'Trinidad and Tobago',
    flag: '🇹🇹',
    isoCode: 'TT',
    iddCode: '+1',
  ),
  Country(name: 'Tuvalu', flag: '🇹🇻', isoCode: 'TV', iddCode: '+688'),
  Country(
    name: 'Taiwan (Province of China)',
    flag: '🇹🇼',
    isoCode: 'TW',
    iddCode: '+886',
  ),
  Country(
    name: 'United Republic of Tanzania',
    flag: '🇹🇿',
    isoCode: 'TZ',
    iddCode: '+255',
  ),
  Country(name: 'Ukraine', flag: '🇺🇦', isoCode: 'UA', iddCode: '+380'),
  Country(name: 'Uganda', flag: '🇺🇬', isoCode: 'UG', iddCode: '+256'),
  Country(
    name: 'United States Minor Outlying Islands',
    flag: '🇺🇲',
    isoCode: 'UM',
    iddCode: '+1',
  ),
  Country(
    name: 'United States of America',
    flag: '🇺🇸',
    isoCode: 'US',
    iddCode: '+1',
  ),
  Country(name: 'Uruguay', flag: '🇺🇾', isoCode: 'UY', iddCode: '+598'),
  Country(name: 'Uzbekistan', flag: '🇺🇿', isoCode: 'UZ', iddCode: '+998'),
  Country(name: 'Holy See', flag: '🇻🇦', isoCode: 'VA', iddCode: '+379'),
  Country(
    name: 'Saint Vincent and The Grenadines',
    flag: '🇻🇨',
    isoCode: 'VC',
    iddCode: '+1',
  ),
  Country(name: 'Venezuela', flag: '🇻🇪', isoCode: 'VE', iddCode: '+58'),
  Country(
    name: 'British Virgin Islands',
    flag: '🇻🇬',
    isoCode: 'VG',
    iddCode: '+1',
  ),
  Country(
    name: 'United States Virgin Islands',
    flag: '🇻🇮',
    isoCode: 'VI',
    iddCode: '+1',
  ),
  Country(name: 'Viet Nam', flag: '🇻🇳', isoCode: 'VN', iddCode: '+84'),
  Country(name: 'Vanuatu', flag: '🇻🇺', isoCode: 'VU', iddCode: '+678'),
  Country(
    name: 'Wallis and Futuna',
    flag: '🇼🇫',
    isoCode: 'WF',
    iddCode: '+681',
  ),
  Country(name: 'Samoa', flag: '🇼🇸', isoCode: 'WS', iddCode: '+685'),
  Country(name: 'Yemen', flag: '🇾🇪', isoCode: 'YE', iddCode: '+967'),
  Country(name: 'Mayotte', flag: '🇾🇹', isoCode: 'YT', iddCode: '+262'),
  Country(name: 'South Africa', flag: '🇿🇦', isoCode: 'ZA', iddCode: '+27'),
  Country(name: 'Zambia', flag: '🇿🇲', isoCode: 'ZM', iddCode: '+260'),
  Country(name: 'Zimbabwe', flag: '🇿🇼', isoCode: 'ZW', iddCode: '+263'),
];
