import 'package:ice/app/features/feed/feed_search/model/feed_search_user.dart';

final feedSearchUsers = [
  FeedSearchUser(
      id: '1',
      nickname: 'cool_cat',
      name: 'Alice Johnson',
      imageUrl: 'https://i.pravatar.cc/150?u=cool_cat',
      isVerified: true),
  FeedSearchUser(
      id: '2',
      nickname: 'sunshine22',
      name: 'Bob Smith',
      imageUrl: 'https://i.pravatar.cc/150?u=sunshine22',
      isVerified: false),
  FeedSearchUser(
      id: '3',
      nickname: 'mountain_lover',
      name: 'Charlie Brown',
      imageUrl: 'https://i.pravatar.cc/150?u=mountain_lover',
      isVerified: true),
  FeedSearchUser(
      id: '4',
      nickname: 'code_wizard',
      name: 'Daniela Gonzalez',
      imageUrl: 'https://i.pravatar.cc/150?u=code_wizard',
      isVerified: false),
  FeedSearchUser(
      id: '5',
      nickname: 'fashionista',
      name: 'Ella Martinez',
      imageUrl: 'https://i.pravatar.cc/150?u=fashionista',
      isVerified: true),
  FeedSearchUser(
      id: '6',
      nickname: 'gamer_guy',
      name: 'Frank Wang',
      imageUrl: 'https://i.pravatar.cc/150?u=gamer_guy',
      isVerified: false),
  FeedSearchUser(
      id: '7',
      nickname: 'coffee_lover',
      name: 'Grace Lee',
      imageUrl: 'https://i.pravatar.cc/150?u=coffee_lover',
      isVerified: true),
  FeedSearchUser(
      id: '8',
      nickname: 'adventure_girl',
      name: 'Hannah Kim',
      imageUrl: 'https://i.pravatar.cc/150?u=adventure_girl',
      isVerified: false),
  FeedSearchUser(
      id: '9',
      nickname: 'techie123',
      name: 'Isaac Patel',
      imageUrl: 'https://i.pravatar.cc/150?u=techie123',
      isVerified: true),
  FeedSearchUser(
      id: '10',
      nickname: 'city_biker',
      name: 'Jasmine Liu',
      imageUrl: 'https://i.pravatar.cc/150?u=city_biker',
      isVerified: false),
  FeedSearchUser(
      id: '11',
      nickname: 'yoga_master',
      name: 'Kevin Smith',
      imageUrl: 'https://i.pravatar.cc/150?u=yoga_master',
      isVerified: true),
  FeedSearchUser(
      id: '12',
      nickname: 'nature_nut',
      name: 'Laura Carter',
      imageUrl: 'https://i.pravatar.cc/150?u=nature_nut',
      isVerified: false),
  FeedSearchUser(
      id: '13',
      nickname: 'bookworm',
      name: 'Michael Nguyen',
      imageUrl: 'https://i.pravatar.cc/150?u=bookworm',
      isVerified: true),
  FeedSearchUser(
      id: '14',
      nickname: 'fitness_freak',
      name: 'Natalie Brown',
      imageUrl: 'https://i.pravatar.cc/150?u=fitness_freak',
      isVerified: false),
  FeedSearchUser(
      id: '15',
      nickname: 'vegan_vibes',
      name: 'Oliver Davis',
      imageUrl: 'https://i.pravatar.cc/150?u=vegan_vibes',
      isVerified: true),
  FeedSearchUser(
      id: '16',
      nickname: 'art_lover',
      name: 'Penelope White',
      imageUrl: 'https://i.pravatar.cc/150?u=art_lover',
      isVerified: false),
  FeedSearchUser(
      id: '17',
      nickname: 'travel_bug',
      name: 'Quincy Martinez',
      imageUrl: 'https://i.pravatar.cc/150?u=travel_bug',
      isVerified: true),
  FeedSearchUser(
      id: '18',
      nickname: 'movie_buff',
      name: 'Riley Jones',
      imageUrl: 'https://i.pravatar.cc/150?u=movie_buff',
      isVerified: false),
  FeedSearchUser(
      id: '19',
      nickname: 'soccer_star',
      name: 'Sophie Johnson',
      imageUrl: 'https://i.pravatar.cc/150?u=soccer_star',
      isVerified: true),
  FeedSearchUser(
      id: '20',
      nickname: 'music_maniac',
      name: 'Tyler Wilson',
      imageUrl: 'https://i.pravatar.cc/150?u=music_maniac',
      isVerified: false),
  FeedSearchUser(
      id: '21',
      nickname: 'dog_lover',
      name: 'Uma Lee',
      imageUrl: 'https://i.pravatar.cc/150?u=dog_lover',
      isVerified: true),
  FeedSearchUser(
      id: '22',
      nickname: 'chef_expert',
      name: 'Victor Garcia',
      imageUrl: 'https://i.pravatar.cc/150?u=chef_expert',
      isVerified: false),
  FeedSearchUser(
      id: '23',
      nickname: 'ocean_dreamer',
      name: 'Willow Johnson',
      imageUrl: 'https://i.pravatar.cc/150?u=ocean_dreamer',
      isVerified: true),
  FeedSearchUser(
      id: '24',
      nickname: 'car_enthusiast',
      name: 'Xander Hall',
      imageUrl: 'https://i.pravatar.cc/150?u=car_enthusiast',
      isVerified: false),
  FeedSearchUser(
      id: '25',
      nickname: 'photog_pro',
      name: 'Yasmin Rivera',
      imageUrl: 'https://i.pravatar.cc/150?u=photog_pro',
      isVerified: true),
  FeedSearchUser(
      id: '26',
      nickname: 'bike_rider',
      name: 'Zachary Green',
      imageUrl: 'https://i.pravatar.cc/150?u=bike_rider',
      isVerified: false),
  FeedSearchUser(
      id: '27',
      nickname: 'foodie_fun',
      name: 'Amy Watson',
      imageUrl: 'https://i.pravatar.cc/150?u=foodie_fun',
      isVerified: true),
  FeedSearchUser(
      id: '28',
      nickname: 'science_geek',
      name: 'Ben Evans',
      imageUrl: 'https://i.pravatar.cc/150?u=science_geek',
      isVerified: false),
  FeedSearchUser(
      id: '29',
      nickname: 'gardener_gal',
      name: 'Carla Jackson',
      imageUrl: 'https://i.pravatar.cc/150?u=gardener_gal',
      isVerified: true),
  FeedSearchUser(
      id: '30',
      nickname: 'skateboarder',
      name: 'Derek King',
      imageUrl: 'https://i.pravatar.cc/150?u=skateboarder',
      isVerified: false),
];
