#!/bin/bash

adb shell setprop log.tag.EGL_emulation "ERROR"
adb shell setprop log.tag.OpenGLRenderer "ERROR"
adb shell setprop log.tag.ViewRootImpl "ERROR"
adb shell setprop log.tag.PipelineWatcher "ERROR"
adb shell setprop log.tag.BufferPoolAccessor2 "ERROR"
adb shell setprop log.tag.BufferPoolAccessor2.0 "ERROR"
adb shell setprop log.tag.Codec2Client "ERROR"
adb shell setprop log.tag.CCodecBuffers "ERROR"
adb shell setprop log.tag.CCodec "ERROR"
adb shell setprop log.tag.ReflectedParamUpdater "ERROR"
adb shell setprop log.tag.MediaCodecUtil "ERROR"
adb shell setprop log.tag.WindowOnBackDispatcher "ERROR"
adb shell setprop log.tag.MediaCodec "ERROR"
adb shell setprop log.tag.CCodecConfig "ERROR"
adb shell setprop log.tag.ImeTracker "ERROR"
adb shell setprop log.tag.InputMethodManager "ERROR"
adb shell setprop log.tag.InputConnectionAdaptor "ERROR"
adb shell setprop log.tag.InsetsController "ERROR"
adb shell setprop log.tag.CCodecBufferChannel "ERROR"
adb shell setprop log.tag.DMCodecAdapterFactory "ERROR"
adb shell setprop log.tag.SurfaceUtils "ERROR"
adb shell setprop log.tag.ColorUtils "ERROR"
adb shell setprop log.tag.ExoPlayerImplInternal "ERROR"
